version: '3'

services:
  database-gesmm:
    container_name: database-gesmm
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gesmm
      TZ: America/New_York
    ports:
      - '5432:5432'
    networks:
      - gesmm
    volumes:
      - gesmm-postgresql:/var/lib/postgresql/data

  database-gesmm-seed:
    build: ./db-seed
    container_name: database-gesmm-seed
    environment:
      WAIT_HOSTS: database-gesmm:5432
    depends_on:
      - database-gesmm
    networks:
      - gesmm

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8080
      DB_VENDOR: postgres
      DB_ADDR: database-gesmm
      DB_PORT: 5432
      DB_DATABASE: gesmm
      DB_SCHEMA: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      TZ: America/New_York
    ports:
      - '8080:8080'
    depends_on:
      - database-gesmm
    networks:
      - gesmm

  backend-gesmm:
    build: ./backend
    container_name: backend-gesmm
    ports:
      - '3333:3333'
    environment:
      WAIT_HOSTS: database-gesmm:5432
    depends_on:
      - database-gesmm
    networks:
      - gesmm
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules/

  frontend-gesmm:
    build: ./frontend
    container_name: frontend-gesmm
    ports:
      - '3000:3000'
      - '35729:35729'
    networks:
      - gesmm
    volumes:
      - ./frontend:/usr/src/app/
      - /usr/src/app/node_modules/

volumes:
  gesmm-postgresql:
    external: true

networks:
  gesmm:
