version: '3'

services:
  database-gesmm:
    container_name: database-gesmm
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gesmm
    ports:
      - '5432:5432'
    networks:
      - gesmm

  database-gesmm-seed:
    build: ./db-seed
    container_name: database-gesmm-seed
    environment:
      WAIT_HOSTS: database-gesmm:5432
    depends_on:
      - database-gesmm
    networks:
      - gesmm

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8080
      DB_VENDOR: postgres
      DB_ADDR: database-gesmm
      DB_PORT: 5432
      DB_DATABASE: gesmm
      DB_SCHEMA: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - '8080:8080'
    depends_on:
      - database-gesmm
    networks:
      - gesmm

networks:
  gesmm:
